apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.elasticsearch.username | b64enc }}
  password: {{ .Values.elasticsearch.password | b64enc }}
