- name: Install Kibana
  hosts: localhost
  vars:
    namespace: monitoring

  tasks:
    - name: Install Openshift Python Library
      command: pip3 install openshift
      delegate_to: localhost

    - name: Install Ansible
      become: true
      apt:
        name: ansible
        state: present
        update_cache: yes
      delegate_to: localhost

    - name: Install Ansible Galaxy Kubernetes
      command: ansible-galaxy collection install community.kubernetes
      delegate_to: localhost

    - name: Create monitoring namespace
      community.kubernetes.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: namespace
        state: present
      delegate_to: localhost

    - name: Copy Customization
      copy:
        src: ../kibana-values.yaml
        dest: /tmp/
      delegate_to: localhost

    - name: Add Elastic Search Repo
      community.kubernetes.helm_repository:
        name: elastic
        repo_url: "https://helm.elastic.co"
      delegate_to: localhost

    - name: Install Kibana
      command: >
        helm install -n "{{ namespace }}"
        kibana elastic/kibana
        -f /tmp/kibana-values.yaml
      delegate_to: localhost
